version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /suites/jwx-v3
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /suites/jwx-v4
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /suites/golang-jwt
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /suites/go-jose
    schedule:
      interval: weekly
