version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /comparison
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /crossversion/v3
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /crossversion/v4
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /performance
    schedule:
      interval: weekly
